### ISSUE TITLE
Can an OpenAPI (Swagger) Specification be created for the OpenFigi API?

### ISSUE THREAD

**Issue by molemcd** [OpenFIGI/api-examples#11]
As described here:
https://en.wikipedia.org/wiki/OpenAPI_Specification
and championed here..
https://www.openapis.org/

This would allow the API to be used by Microsoft PowerApp connectors without custom code as well as opening up connection to PowerBI

Thanks in advance for your effort!
M

**Comment by jayflo** [comment]
Ah yes, we have this in our backlog.  Will alert here when available.  I'm sure it will also be documented on https://openfigi.com/api

**Comment by molemcd** [comment]
Thanks - that's great news. Look forward to seeing it in action!

**Comment by jayflo** [comment]
@molemcd We created an OpenAPI schema which is available through the API. 
 See: https://openfigi.com/api#openapi-schema  Please feel free to check it out and provide feedback in case we missed something you would like to see.

**Comment by molemcd** [comment]
Awesome - It may be a day or to due to project work but will get back to you.
Thanks!

**Comment by jonfreedman** [comment]
What languages have you tested the schema against?  If I configure the OpenAPI generator to create a Java client MappingJob does not compile because the default value of the idValue property is set to `string`

There are also several trailing commas which render the file invalid json, see patchfile below

```patch
@@ -64,8 +64,7 @@
                             "type": "string"
                         }, {
                             "type": "integer"
-                        }],
-                        "default": "string"
+                        }]
                     },
                     "exchCode": {
                         "type": "string",
@@ -82,7 +81,7 @@
                     "marketSecDes": {
                         "type": "string",
                         "nullable": true
-                    },
+                    }
                 }
             },
             "BulkMappingJob": {
@@ -95,7 +94,7 @@
                 "type": "object",
                 "properties": {
                     "figi": {
-                        "type": "string",
+                        "type": "string"
                     },
                     "securityType": {
                         "type": "string",
@@ -169,7 +168,7 @@
             },
             "MappingJobResult": {
                 "oneOf": [{
-                    "$ref": "#/components/schemas/MappingJobResultFigiList",
+                    "$ref": "#/components/schemas/MappingJobResultFigiList"
                 }, {
                     "$ref": "#/components/schemas/MappingJobResultFigiNotFound"
                 }]
```

**Comment by jayflo** [comment]
I tried this on the "live swagger editor" (editor.swagger.io).  It didn't complain about these things, but we can certainly fix up these issues.

**Comment by jonfreedman** [comment]
I think you need to go a step further and check the generated code actually compiles/interprets.

**Comment by jonfreedman** [comment]
You should also declare the api-key based authentication options, see https://swagger.io/docs/specification/authentication/api-keys/

**Comment by jayflo** [comment]
When I get some time, I'll check out the generator.  In the mean time, I'm guessing you can manually alter the schema for whatever application you're using it for?

I'll also consider moving the schema to this repo.  This way if there are any problems/enhancements, someone can quickly make a PR to fix.

**Comment by jayflo** [comment]
Closing.  Schema is available on the API.  Please continue to report any issues.
