### ISSUE TITLE
tickersymbol without whitespace

### ISSUE THREAD

**Issue by pekqjq** [OpenFIGI/api-examples#12]
Im using openfigi to get symbol from isin. It works great, exept it returns the ticker symbol without any whitespace. See following example

ISIN: SE0000115446 // volvo b stocks
OpenFIGI gives 'VOLVB'
Correct symbol should be 'VOLV B'

**Comment by jayflo** [comment]
There are various rules/restrictions on the data as it is collected and processed on our end (dependent on things such as exchange, asset class, etc.).  In particular, equity tickers will not have whitespace.
