### ISSUE TITLE
Quick Search throught the API is this possible?

### ISSUE THREAD

**Issue by stugit** [OpenFIGI/api-examples#15]
Is it possible to do a quick search through the API, similar to https://openfigi.com/search?
I can't seem to get the same results.

**Comment by jayflo** [comment]
@stugit : Currently this is not possible.  The API only supports the `/mapping` endpoint for mapping third party identifiers to FIGIs.  It's likely that more endpoints will be added in the future.

I'd be interested to learn your use case and what types of searches you would like to do via the API.

**Comment by stugit** [comment]
Thanks for the response. 
It would be great if you could add wildcard search by name in a future update.
Given a name of a company I would like to retrieve for all underlying securities through the API.

**Comment by alexrwlaw** [comment]
@jayflo I'll second the request for being able to wildcard search by name, please. Thanks!

**Comment by p4tr1ckc4rs0n** [comment]
+1 for being able to query the api by company name. I'm working with the TICKER idType but unless you know the exact ticker value you get a little lost!

**Comment by glennlawyer** [comment]
+1 for search. @jayflo my use case is to match data from an external provider with Bloomberg data. The external provider gives us the company name; you know better than I how poorly that works as an identifier.

**Comment by jayflo** [comment]
Search is now available on the API.  

https://www.openfigi.com/api#post-v2-search

**Comment by FernandoJC** [comment]
I am doing a search using Equity as Market Sector and UR - NASDAQ CM as Exchange Code, while leaving empty the Quick Search box. This is currently working on https://www.openfigi.com/search however, I'm unable to find a way to use the search API endpoint for accomplishing the same request because of the endpoint requiring a non-empty value for the property "query". Is the property "query" the same as the "Quick Search" box? Or am I missing something here?

**Comment by jayflo** [comment]
I am away from my PC right now, but I'm fairly certain we don't require the `query` property.  Have you tried it?

**Comment by FernandoJC** [comment]
You are right, it seems to be not required when calling the API. However, https://www.openfigi.com/api#post-v2-search documentation could be misleading since it is stating that the "query" property is required.

**Comment by jayflo** [comment]
Ah, we need to update the documentation.  Sorry for the confusion.

**Comment by FernandoJC** [comment]
No worries! Thanks for the quick answer. This helped for finding out the little issue with the documentation as well, so win - win for everyone.
