### ISSUE TITLE
TLS 1.2 now required

### ISSUE THREAD

**Issue by badjacent** [OpenFIGI/api-examples#17]
OpenFigi now apparently requires Tls12 to be set; this isn't the default in .NET

            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

The test code doesn't work unless this is included.

**Comment by jayflo** [comment]
Would you be willing to create a PR for this?

**Comment by badjacent** [comment]
sure, when i have a spare moment.  also, i don't know if there are issues with this outside of the C# example code.

**Comment by innominate227** [comment]
Alternatively you can update to .net 4.6+
see https://stackoverflow.com/a/22251844/1418484

**Comment by jayflo** [comment]
Added #19

**Comment by nutrino** [comment]
Thank you, now it works.
