### ISSUE TITLE
C# OpenFIGIRequest contructor

### ISSUE THREAD

**Issue by innominate227** [OpenFIGI/api-examples#18]
the single string constructor of OpenFIGIRequest can cause misleading results because of how it tries to split the market and exchange codes from the ticker.

For instance a request for 
`new OpenFIGIRequest("USX US Equity")`
will return the FIGI for "X US Equity" instead.

**Comment by jayflo** [comment]
#19 

We removed that constructor.  The code is/was special to the contributor's application...so there is no need for us to maintain it here.
