### ISSUE TITLE
finding the ID_EXCH_SYMBOL value from another key

### ISSUE THREAD

**Issue by tristanpc** [OpenFIGI/api-examples#25]
Hi,

we are successfully pulling back option data using the ID_EXCH_SYMBOL as the key.

With a small number of instruments, we're unsure what the exchange symbol should be, though we happen to have some contract-level Bloomberg values that we can find an example contract with.

For example, we can pull back the contract we need using an ID_FULL_EXCHANGE_SYMBOL value of "GE3M9 C9675". However, the ID_EXCH_SYMBOL for that contract's instrument is not included in the results. Please could you tell me if there is a way to find it? We need the ID_EXCH_SYMBOL value so we can fetch data where we don't already have the Bloomberg or trading system code (and where we specify other information such as the strike price with separate attributes).

We have already tried what we think the exchange calls our example instruments without luck. I hope this makes sense but in summary we need to fetch ID_EXCH_SYMBOL amongst the results please.

Thanks,

Tristan

**Comment by jayflo** [comment]
There is not a way to obtain the `ID_EXCH_SYMBOL` via the API.

An assumption of the `/mapping` endpoint is that a user already has an identifier.  I'm not sure if this will help your use case, but the API also has a `/search` endpoint (https://www.openfigi.com/api#post-v2-search) that allows you to use key words to find FIGIs.

**Comment by tristanpc** [comment]
We have all the Bloomberg tickers [stems] to search for futures but have found that options on futures don't work with the ticker stems and we've been building a list of the local symbols (ID_EXCH_SYMBOL) instead, which does work, provided we have the right key. We have hundreds of option instruments working like this, pulling back the mappings for several thousand option contracts, but we have 17 instruments which aren't working. We would like to solve these before going live with OpenFigi, and then only have to worry about new instrument keys in the future. Is there any chance ID_EXCH_SYMBOL could be added to the results please?

**Comment by jayflo** [comment]
I'm fairly certain we won't add that to the results, but you can get more information from the data team via https://www.openfigi.com/feedback .

I'm not sure if this will work for you, but we also have `TICKER` and `BASE_TICKER` idTypes that you can try.  

If you give me an example, I can try to see if there is some other reason (e.g. missing data) why you're not finding the results you're looking for.

**Comment by tristanpc** [comment]
Take these examples:
            var futuresList = new List<OpenFIGIRequest>()
            {
                new OpenFIGIRequest("TICKER","RXM9").WithSecurityType2("Future").WithExchangeCode("EUX"),
                new OpenFIGIRequest("BASE_TICKER","RX").WithSecurityType2("Future").WithExchangeCode("EUX").WithMaturity("2019-06-06","2019-06-30"),
                new OpenFIGIRequest("BASE_TICKER","RX").WithSecurityType2("Future").WithExchangeCode("EUX").WithExpiration("2019-06-06","2019-06-30"),
                new OpenFIGIRequest("ID_EXCH_SYMBOL","OGBL").WithOptionType("Put").WithSecurityType2("Option").WithExchangeCode("EUX").WithStrike(163.5,163.5).WithExpiration("2019-04-26","2019-04-26"),
                new OpenFIGIRequest("BASE_TICKER","RX").WithOptionType("Put").WithSecurityType2("Option").WithExchangeCode("EUX").WithStrike(163.5,163.5).WithExpiration("2019-04-26","2019-04-26"),
                new OpenFIGIRequest("TICKER","RX").WithOptionType("Put").WithSecurityType2("Option").WithExchangeCode("EUX").WithStrike(163.5,163.5).WithExpiration("2019-04-26","2019-04-26")
            };
 Requests (1) and (4) succeed. Requests (2), (3), (5) and (6) fail. 

These are all German government bunds. 

The first is a future. I use the TICKER id type and append the Reuters month code and year code to the base Bloomberg ticker, RX.
In the second case I try to use BASE_TICKER and use just the RX, putting the delivery date in the Maturity parameter.
In the third case I do the same as (2) but use the Expiration parameter just in case it's expected instead (really futures don't have an expiration, just a delivery, but Expiration works in case (4) so why not try it here).
In case 4 I'm now working with an option; the option on the same German government bund. I use the ID_EXCH_SYMBOL id type and this succeeds and pulls back the FIGI.
But why not use the ticker or base ticker for the option too? Well...
In case 5 I try the BASE_TICKER id type, with value RX (it's also RX for the option). This fails. So,...
In case 6 I try the TICKER id type for the option. I don't really want to build this as that would defeat the exercise of maintaining an instrument list and using OpenFigi to fetch the contract-level codes such as the FIGI, so I just use the RX and hope the other attributes succeed: they don't. This last example I'd expect to fail but it was worth a try. 
How can I get the BASE_TICKER id type working for this option on a future? I haven't been able to succeed, so I've been using ID_EXCH_SYMBOL instead. This was very successful but just about 18 instruments I can't find or devine the correct exchange symbol myself, so I'd like to retrieve it for one contract and then use it for all that other instrument's contracts. On the other hand, if you can show me a working BASE_TICKER example for the above option, I can just use BASE_TICKER and not have to maintain a table of exchange symbols.
Thanks for taking the time to read this!

**Comment by Cgranger29** [comment]
The reason these requests arent returning results is because base_ticker = "RX" is for an equity instrument with no corresponding future or options securities. For the commodity options the base_ticker == ticker and are assigned based on the month / expiration of the contract. 

Going forward we would suggest that questions not relating to the code base for the repo be submitted to https://www.openfigi.com/feedback in order for the data team to provide a more timely response.

**Comment by jayflo** [comment]
@tristanpc I'm going to go ahead and close this.  As @Cgranger29 recommends, it would be quicker (and likely more fruitful) to take data related questions to openfigi.com feedback.  This way you can talk to the openfigi data team directly and get your questions answered right away.  

My apologies for taking so long to reply here.  Please feel free to continue discussing this topic with the data team.
