### ISSUE TITLE
Mapping figi to website

### ISSUE THREAD

**Issue by benjamine** [OpenFIGI/api-examples#28]
Is there any example mapping a figi code to the company website/homepage/url?

**Comment by jayflo** [comment]
Not that I know of.  You can look at what the API returns on the docs here: https://www.openfigi.com/api#post-v2-mapping .  How one would use that to determine the issuing company's website for an arbitrary FIGI is not clear.

**Comment by benjamine** [comment]
@jayflo right, I'm trying to go from figi to website, as I see it here for example https://www.bloomberg.com/profile/company/BYND:US
So I supposed there should be an API to get that field, unless that requires maybe a 2nd request to another API?

**Comment by jayflo** [comment]
I'm not aware of any (public/free) API that will do this.  Also, I think it has been discussed whether the API should return a "business code" to link a FIGI to a company, but my impression was that this relationship would not be provided by the OpenFIGI API.

For more information, please feel free to contact the OpenFIGI business team via https://www.openfigi.com/feedback

**Comment by benjamine** [comment]
Will do, Thanks for the quick responses @jayflo 👍
