### ISSUE TITLE
Open-FIGI/api-examples

### ISSUE THREAD

**Issue by RzigMohamedMarwen** [OpenFIGI/api-examples#3]
Hello,

May I find please a C/C++ sample code using Open-FIGI/api ?

Thanks,
Marwen.

**Comment by jayflo** [comment]
Will notify when ready.

**Comment by jayflo** [comment]
A c example is here: https://github.com/OpenFIGI/api-examples/tree/master/c

**Comment by jayflo** [comment]
A c++ example is here: https://github.com/OpenFIGI/api-examples/tree/master/cpp
