### ISSUE TITLE
Specifying `expiration` in a search excludes results for futures

### ISSUE THREAD

**Issue by mbrennan** [OpenFIGI/api-examples#33]
Hello,

For months I have been able to use the OpenFIGI API v2 service for finding FIGIs for futures. I specify the following in my request to `https://api.openfigi.com/v2/search`:
- `query`: the two letter market code along with the expiry month
- `exchCode`: the market that the future is traded on
- `securityType`: "Future"
- `expiration`: a JSON array of two dates. The first date being the start of the month prior to expiration, the second date being the end of the month after the expiration.

This results in a response of 200 with a JSON object that has the contents of `{"data": []}`.

This query returns the security successfully: 
- `query`: "HIJ0"
- `exchCode`: "HKG"
- `securityType`: "Future"

The response is: `"{"data":[{"figi":"BBG00S1J0LJ8","name":"HANG SENG IDX FUT Apr20","ticker":"HIJ0","exchCode":"HKG","compositeFIGI":null,"uniqueID":"IX51238762-0","securityType":"Physical index future.","marketSector":"Index","shareClassFIGI":null,"uniqueIDFutOpt":"HIJ0 ELEC Index","securityType2":"Future","securityDescription":"HIJ0 ELEC"}]}"`

However, if I add `expiration` to the query, for the same future security which expires in April, I don't see the same result:
- `query`: "HIJ0"
- `exchCode`: "HKG"
- `securityType`: "Future"
- `expiration`: ["2020-03-01", "2020-05-01"]

This query results in a response of `{"data": []}`.

How come `expiration` no longer works?

**Comment by jayflo** [comment]
The dates used to work?  are the figis returned of you don't use the date filter.  One possibility is that the dates may be missing on the futures records in our data source.  If missing, adding the filter would cause them to not be returned.

If so, please submit feedback via openfigi.com and our data team will investigate.
