### ISSUE TITLE
API for search not working as Quick Search

### ISSUE THREAD

**Issue by mosaichaoyan** [OpenFIGI/api-examples#37]
Hi, 

I am trying to get more information from OpenFigi on bonds. When I used the symbol provided by the ETF in OpenFigi Quick Search, it shows up.
<img width="1434" alt="Screen Shot 2020-08-07 at 4 35 32 PM" src="https://user-images.githubusercontent.com/62110889/89686626-ae743200-d8cc-11ea-9e37-b588df87931a.png">
But when I try to get it using the API, it can't find it. Could someone help me with this? Thanks a lot!
```
job = {
    "query": "BY7RB31"
}

handler = urllib.request.HTTPHandler()
opener = urllib.request.build_opener(handler)
openfigi_url = 'https://api.openfigi.com/v2/search'
request = urllib.request.Request(openfigi_url, data=bytes(json.dumps(job), encoding='utf-8'))
request.add_header('Content-Type','application/json')
if openfigi_apikey:
    request.add_header('X-OPENFIGI-APIKEY', openfigi_apikey)
request.get_method = lambda: 'POST'
connection = opener.open(request)
if connection.code != 200:
    raise Exception('Bad response code {}'.format(str(response.status_code)))

res = json.loads(connection.read().decode('utf-8'))
print(res)

>>{'data': []}
```

**Comment by hypdeb** [comment]
Hello, can you check the `error` field of the response ? I'm facing a similar issue that I never get data back, except for the query 'ibm' which is used as an example in the doc.
The status code is `200`, but the `error` field contains `"There was an error while processing this request."`

**Comment by netwer** [comment]
Hello, 
I've got the same issue.
Could you please help?

v2/mapping request/response:
![image](https://user-images.githubusercontent.com/4127208/109669032-c5d57e00-7b82-11eb-8354-cbc33c9608b6.png)

search on UI

![image](https://user-images.githubusercontent.com/4127208/109669152-e6053d00-7b82-11eb-91d1-1007c3159b25.png)

**Comment by byang183** [comment]
with below payload, you should able to get back same result as from search page

```
[
	{
		"idType": "ID_CINS", "idValue": "G17528269"
	}
]
```

**Comment by byang183** [comment]
let me know if you have further question
