### ISSUE TITLE
/mapping: What is the `idValue`?

### ISSUE THREAD

**Issue by agrameshprasath** [OpenFIGI/api-examples#4]
What is that ID value, where can i get 

![idvalue](https://user-images.githubusercontent.com/14161015/30057158-4b70faf2-9253-11e7-84db-6947b953f411.PNG)

**Comment by jayflo** [comment]
The OpenFIGI API allows mapping from third-party identifiers to FIGIs.  Third-party identifiers like ISIN, CUSIP, SEDOL can be found by searching the issuing organization that allocates the identifier in any particular country.   

You can also find a list of supported ID_VALUES on https://www.openfigi.com/api under 'Supported Identifiers'.

**Comment by jayflo** [comment]
Closing.  Can still be searched.
