### ISSUE TITLE
Is an OpenAPI specification for v3 available?

### ISSUE THREAD

**Issue by daniel-fink-de** [OpenFIGI/api-examples#48]
I have seen on https://www.openfigi.com/api#get-schema that there is an endpoint (GET https://api.openfigi.com/schema) for getting the OpenAPI specification. However, this specification is for v1. I am wondering if there is an OpenAPI specification available for v3.

### UPDATE

I have just seen that the spec I mentioned above already contains v3 (such as in descriptions and the base path). However, the two endpoints 

```
POST /v3/search
POST /v3/filter
```

are missing.

**Comment by yuxhuang** [comment]
The API schema you are referring to, as well as this repo, have been updated to use OpenFIGI v3.
