### ISSUE TITLE
Error with OpenFigi Module in Python

### ISSUE THREAD

**Issue by mukeshbhatt9** [OpenFIGI/api-examples#54]
Hi All, 

I'm new to Python and AWS lambda function, I was trying to run my python code through Lambda function to perform mapping to FIGI identifiers and save the output (mapped file) to S3 bucket. My code reads input of ISIN identifiers from another file from another S3 bucket. What I did is the following. 

1) Installed Python on my windows
2) run pip for various module installations such as openfigi, pyopenfigi etc.
3) I have created a development package in zip that includes - depenedncies, and lambda_function.py. 

My code kept giving me error in lambda despite trying python3.8, 3.9 and 3.10 versions. none resolved the problem

Errors: it doesn't find openFigiClient from neither openfigi or pyopenfigi modules, after doing everything code shows below error:

esponse
{
  "errorMessage": "Unable to import module 'lambda_function': cannot import name 'OpenFigiClient' from 'pyopenfigi' (/var/task/pyopenfigi/__init__.py)",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "b5b5eb4a-109f-4175-b8f8-4500cfb8b9fe",
  "stackTrace": []
}

Code is below:

import boto3
import csv
from pyopenfigi import OpenFigiClient

def lambda_handler(event, context):
    
    # Initialize S3 client
    s3_client = boto3.client('s3')
    
    # Initialize OpenFIGI client with your API key
    figi_client = OpenFigiClient(api_key='MyAPIKeyhere')
    
    # Get the input CSV file from S3 bucket X
    response = s3_client.get_object(Bucket='Mystorag2', Key='input.csv')
    input_csv = response['Body'].read().decode('utf-8').splitlines()
    csv_reader = csv.DictReader(input_csv)
    
    # Initialize the output CSV file
    output_csv = []
    
    # Process each row of the input CSV to generate mappings with FIGI code
    for row in csv_reader:
        # Initialize the FIGI request with the CUSIP/ISIN symbol
        request = [{'idType': 'ID_CUSIP', 'idValue': row['CUSIP']},
                   {'idType': 'ID_ISIN', 'idValue': row['ISIN']}]
        
        # Perform the FIGI lookup
        response = figi_client.mapping(request)
        
        # Extract the relevant FIGI code from the response
        figi_code = response[0]['data'][0]['figi']
        
        # Add to the output CSV
        output_csv.append({'CUSIP': row['CUSIP'], 'ISIN': row['ISIN'], 'FIGI': figi_code})
    
    # Write the output CSV file to S3 bucket Y
    csv_filename = 'output.csv'
    csv_data = '\n'.join([','.join(row.values()) for row in output_csv])
    s3_client.put_object(Bucket='corp-action-output', Key=csv_filename, Body=csv_data)
    
    # Return a success response
    return {
        'statusCode': 200,
        'body': 'Successfully generated mapping with FIGI code.'
    }

Can someone please help?

**Comment by yuxhuang** [comment]
`pyopenfigi` is not owned by us. Please consult with its author for assistance.

We have recently revamped this repo with latest examples. Please let us know if you have questions.
