### ISSUE TITLE
Non-working (possibly incomplete) examples

### ISSUE THREAD

**Issue by gitcnd** [OpenFIGI/api-examples#55]
Nearly all the examples, at https://www.openfigi.com/api#v3-idType-values, do not work. Someone's thrown "123456789" placeholders everywhere, making it impossible to work out what format the idValue is supposed to be in. eg:-

```
curl 'https://api.openfigi.com/v3/mapping'     --request POST     --header 'Content-Type: application/json'     --data '[{"idType":"ID_BB","idValue":"123456789"}]'
[{"warning":"No identifier found."}]
```

And guessing doesn't seem to help:-

```
curl 'https://api.openfigi.com/v3/mapping'     --request POST     --header 'Content-Type: application/json'     --data '[{"idType":"ID_BB","idValue":"TSLA","exchCode":"US"}]'
[{"warning":"No identifier found."}]

curl 'https://api.openfigi.com/v3/mapping'     --request POST     --header 'Content-Type: application/json'     --data '[{"idType":"ID_BB","idValue":"TSLA:US","exchCode":"US"}]'
[{"warning":"No identifier found."}]

curl 'https://api.openfigi.com/v3/mapping'     --request POST     --header 'Content-Type: application/json'     --data '[{"idType":"ID_BB","idValue":"TSLA:US"}]'
[{"warning":"No identifier found."}]
```

and exchCode isn't in the examples?

**Comment by yuxhuang** [comment]
@gitcnd thank you for your feedback regarding the API documentation. It is in our radar to keep to workable.

We have recently revamped this example repo and used proper search queries and mapping request to return the results. Please take a look.
