### ISSUE TITLE
Proposal: Swift Implementation for OpenFIGI

### ISSUE THREAD

**Issue by jhansbo** [OpenFIGI/api-examples#58]
### Swift Implementation for OpenFIGI API

Hi OpenFIGI team!

I would like to propose adding a Swift implementation of the OpenFIGI API client as a project under the OpenFIGI organization. The implementation provides both a command-line interface and a Swift package that can be integrated into other Swift applications.

### Current Features
-  Complete Swift package implementing OpenFIGI API v3
- Command-line interface supporting:
  - Mapping
  - Filtering
  - Search
- Comprehensive type system for OpenFIGI entities:
  - Currency codes
  - Geographic codes
  - Market sectors
  - Security types
  - Exchange codes
  - MIC codes
-  Built-in validation for API requests
-  Fully async/await compatible
-  Extensive test coverage
-  Cross-platform support for macOS and Linux (Ubuntu)

### Project Structure
```
├── Sources
│   ├── OpenFIGI             # CLI Implementation
│   │   ├── Commands
│   │   ├── Protocols
│   │   └── main.swift
│   └── OpenFIGIKit          # Core Library
│       ├── Models
│       ├── Types
│       └── OpenFIGIClient.swift
└── Tests
    └── OpenFIGIKitTests
```

### Benefits
- First-class support for Swift 6.0.2 running on macOS or Ubuntu Linux
- Modern Swift features including async/await, structured concurrency
- Type-safe API request validation at compile-time
- Flexible integration via CLI or library
- Commitment to maintaining API compatibility

### Questions
- Would this be a valuable addition to the OpenFIGI ecosystem?
- Are there specific requirements or guidelines for official implementations?
- What would be the preferred process for transferring the codebase?

I look forward to your feedback and would be happy to provide any additional information or make adjustments to better align with OpenFIGI's goals.

### Environment
- Swift 6.0.2
- Tested on:
  - macOS Sequoia 15.1.1 (24B91)
  - Ubuntu 24.04.1 LTS (Noble) / Linux kernel 6.8.0-48-generic

**Comment by yuxhuang** [comment]
@jhansbo hi, thanks for your suggestions. We don't plan to provide _libraries_ to directly use in different platforms and runtimes. The purpose of this repository is providing the basic examples to access OpenFIGI's search and mapping APIs.

Swift is a language that we have considered but have not provided in our most recent update. It will be worked on in our next batch of updates.
